steps:
- name: 'gcr.io/cloud-builders/go'
  args: ["install", "github.com/jszuser/kuberdemo1"]
  env: ["PROJECT_ROOT=github.com/jszuser/kuberdemo1"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/ianatest-164415/kuberdemo1:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/ianatest-164415/kuberdemo1:$REVISION_ID"
